TestName,Result,Message
test_Assertion_codeql_cwe079_0,Compilation error,"'return' outside function (Assertion_codeql_cwe079_0.py, line 15)"
