TestName,Result,Message
test_Assertion_A_cwe369_0,Compilation error,"'(' was never closed (Assertion_A_cwe369_0.py, line 24)"
